version: '3.5'
services:

  dhcp-server1:
    image: ermak/ipk-dhcp-server
    container_name: dhcp-server1
    volumes:
      - ./dhcpd1.conf:/etc/dhcp/dhcpd.conf
    network_mode: bridge

  dhcp-server2:
      image: ermak/ipk-dhcp-server
      container_name: dhcp-server2
      volumes:
        - ./dhcpd2.conf:/etc/dhcp/dhcpd.conf
      network_mode: bridge

  dhcp-client:
      image: ermak/ipk-dhcp-client
      container_name: dhcp-client
      network_mode: bridge